apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eosrate-storage
parameters:
  fromBackup: ""
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true