name: box

on:
    push:
        branches:
            - main
            - "test/*"
    pull_request:
        types: [assigned, opened, synchronize, reopened, labeled]
        paths:
            # - "docker/eden-webapp.Dockerfile"
            - ".eslintignore"
            - ".eslintrc.js"
            - ".prettierrc.json"
            - "lerna.json"
            - "packages/box"
            - "package.json"
            - "tsconfig.build.json"
            - "tsconfig.json"
            - "yarn.lock"

jobs:
    box-e2e:
        name: Eden Box E2E Tests
        runs-on: ubuntu-latest

        steps:
            - name: âœ… Checkout code
              uses: actions/checkout@v2

            - name: ðŸ›  Build and Start Box
              run: |
                  yarn
                  cd packages/box
                  yarn build
                  yarn start &

            - name: ðŸ§ª Run E2E
              # TODO: add real E2E tests... for now it's just a shameless curl ping
              run: |
                  curl localhost:3032

    box-build:
        needs: box-e2e
        name: Build Eden Box
        runs-on: ubuntu-latest

        steps:
            - name: âœ… Checkout code
              uses: actions/checkout@v2

            - name: Image Preparation
              id: prep
              run: |
                  REGISTRY="ghcr.io"
                  IMAGE="${REGISTRY}/${{ github.repository_owner }}/eden-box"
                  TAGS="${IMAGE}:${{ github.sha }}"
                  if [[ $GITHUB_REF == ref/head/master ]]; then
                    TAGS="${TAGS},${IMAGE}:latest"
                  fi
                  echo ::set-output name=tags::${TAGS,,}

            - name: Showtag
              id: showtag
              run: echo ${{ steps.prep.outputs.tags }}

            - name: Docker Buildx setup
              uses: docker/setup-buildx-action@v1

            - name: Login in to registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: ðŸ›  Build & Publish Image
              uses: docker/build-push-action@v2
              with:
                  # push: true # TODO: follow up on this... https://github.community/t/403-error-on-container-registry-push-from-github-action/173071/5
                  file: docker/eden-box.Dockerfile
                  tags: ${{ steps.prep.outputs.tags }}
