name: webapp

on:
    push:
        branches:
            - main
            - "test/*"
    pull_request:
        types: [assigned, opened, synchronize, reopened, labeled]
        paths:
            - "docker/eden-webapp.Dockerfile"
            - ".eslintignore"
            - ".eslintrc.js"
            - ".prettierrc.json"
            - "lerna.json"
            - "packages/webapp"
            - "package.json"
            - "tsconfig.build.json"
            - "tsconfig.json"
            - "yarn.lock"

jobs:
    webapp-e2e:
        name: WebApp E2E Tests
        runs-on: ubuntu-latest

        steps:
            - name: âœ… Checkout code
              uses: actions/checkout@v2

            - name: ðŸ›  Build and Start WebApp
              run: |
                  yarn
                  yarn build --stream
                  yarn start --stream &

            - name: ðŸ§ª Run E2E
              run: |
                  yarn test --stream

            - name: ðŸŽ¥ Upload Cypress Results
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: Cypress E2E Videos and Screenshots
                  path: |
                      packages/webapp/cypress/screenshots
                      packages/webapp/cypress/videos

    webapp-build:
        needs: webapp-e2e
        name: Build Eden Community WebApp
        runs-on: ubuntu-latest

        steps:
            - name: âœ… Checkout code
              uses: actions/checkout@v2

            - name: Image Preparation
              id: prep
              run: |
                  REGISTRY="ghcr.io"
                  IMAGE="${REGISTRY}/${{ github.repository_owner }}/eden-webapp"
                  TAGS="${IMAGE}:${{ github.sha }}"
                  if [[ $GITHUB_REF == ref/head/master ]]; then
                    TAGS="${TAGS},${IMAGE}:latest"
                  fi
                  echo ::set-output name=tags::${TAGS,,}

            - name: Showtag
              id: showtag
              run: echo ${{ steps.prep.outputs.tags }}

            - name: Docker Buildx setup
              uses: docker/setup-buildx-action@v1

            - name: Login in to registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: ðŸ›  Build & Publish Image
              uses: docker/build-push-action@v2
              with:
                  # push: true # TODO: follow up on this... https://github.community/t/403-error-on-container-registry-push-from-github-action/173071/5
                  file: docker/eden-webapp.Dockerfile
                  tags: ${{ steps.prep.outputs.tags }}
