name: eden-webapp container

on:
    push:
        branches:
            - main
            - "test/*"
        paths:
            - "docker/eden-webapp.Dockerfile"
    pull_request:
        types: [assigned, opened, synchronize, reopened, labeled]
        paths:
            - "docker/eden-webapp.Dockerfile"

jobs:
    build:
        name: Updates Eden Builder Image
        runs-on: ubuntu-latest

        steps:
            - name: âœ… Checkout code
              uses: actions/checkout@v2

            - name: Preparation
              id: prep
              run: |
                  REGISTRY="ghcr.io"
                  IMAGE="${REGISTRY}/${{ github.repository_owner }}/eden-webapp"
                  TAGS="${IMAGE}:${{ github.sha }}"
                  if [[ $GITHUB_REF == ref/head/master ]]; then
                    TAGS="${TAGS},${IMAGE}:latest"
                  fi
                  echo ::set-output name=tags::${TAGS,,}

            - name: Showtag
              id: showtag
              run: echo ${{ steps.prep.outputs.tags }}

            - name: Docker Buildx setup
              uses: docker/setup-buildx-action@v1

            - name: Login in to registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: ðŸ›  Build & Publish Image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  file: docker/eden-webapp.Dockerfile
                  tags: ${{ steps.prep.outputs.tags }}
